name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_FILE: "Practice1.csproj"  # 👈 match the filename you just created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "$PROJECT_FILE"

      - name: Build
        run: dotnet build "$PROJECT_FILE" -c Release --no-restore

      - name: Test (if any)
        run: dotnet test -c Release --no-build || echo "No tests"

      - name: Publish
        run: dotnet publish "$PROJECT_FILE" -c Release -o out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: out/**
