name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest # or ubuntu-latest, both are fine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # This step is safe even if you don't have tests; it will just do nothing.
      - name: Test (if any)
        run: dotnet test --configuration Release --no-build || echo "No tests"

      # Creates a ready-to-run build and uploads it as a downloadable artifact.
      - name: Publish
        run: dotnet publish **/*.csproj -c Release -o out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: out/**


